### ISSUE TITLE
Practical example?

### ISSUE THREAD

**Issue by datascribbler777** [GiovanniDicanio/Utf8Conv#1]
Hello Giovanni,

I am a longtime fan of yours from the Pluralsight courses on C++. I am fairly new to C++. I was wondering if you could add a practical example of your library in action. 

I have been trying to use it but I am very confused as to what Utf8, Utf16, Unicode, and C++ are doing together.

I have tried converting a normal std::string(utf8 by default in C++? I think) to a std::wstring(utf16 in C++?  Not sure) but I get no output when I try to print the converted wstring. 
```
std::string data8 = "Hello";
std::wstring data16 = Utf8Conv::Utf8ToUtf16(data8);
```
What am I doing wrong?

**Edit: I had a unicode character in a string and print out prior to this code.  After deleting that, the conversion seems to be working correctly and printing fine.

**Comment by GiovanniDicanio** [comment]
Hi,

I'm very happy that you like my Pluralsight courses on C++. Thank you very much for your compliments.

You can definitely use `std::string` to store UTF-8-encoded text, an `std::wstring` to store UTF-16-encoded text.

There are many examples that could be done to show such Unicode conversions in action.
For instance, you can consider a blog post I wrote about printing Unicode UTF-8 text to the Windows Command Prompt:

https://blogs.msmvps.com/gdicanio/2019/04/09/printing-utf-8-text-to-the-windows-console-sample-code/

The idea is that, if you have a UTF-8-encoded text stored in a `std::string` instance, you can convert it to UTF-16 using `Utf8ToUtf16()`, and then print the UTF-16-encoded text using `std::wcout`.

Note that, at least at the time of writing those posts, _direct_ UTF-8 output to the Windows command prompt was _not_ supported, as you got a Visual C++ Runtime Library crash, as documented in this other blog post:

https://blogs.msmvps.com/gdicanio/2017/08/22/printing-utf-8-text-to-the-windows-console/

So you have to go from UTF-8 to UTF-16, and then print the UTF-16 encoded text to the console.

In addition, if you work on GUI Windows programs written in C++ (e.g. using MFC, or ATL/WTL), you can have UTF-8-encoded text stored in `std::string` objects in cross-platform parts of your C++ code, but you have to convert to UTF-16 to properly show international text in the GUI of your Windows programs.

I may add some GUI examples in the future, when I have some spare time.
